version: '2'
services:
  scheduling:
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.npm
    command: npm run test
    environment:
      - NODE_ENV=test
      - MONGOLAB_URI=mongodb://mongo/repairly-routing-dev
  mongo:
    image: mongo
    ports:
      - "9000"
