version: '2'
services:
  scheduling:
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.npm
    command: ["npm", "start"]
    environment:
      - MONGOLAB_URI=mongodb://mongo/repairly-routing-dev
      - MONGOLAB_URI_TEST=mongodb://mongo/repairly-routing-test
  mongo:
    image: mongo
    ports:
      - "9000"
